
spring:
  freemarker:
    requestContextAttribute: request

exp-platform:
  datasource:
    url: jdbc:mysql://192.168.1.24:3306/icon
    username: cartoon
    password: cartoon
    driverClassName: com.mysql.jdbc.Driver

session:
  interval: 900
